name: 最新博客自动更新

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: 获取博客文章
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://xifeng.net/rss.xml"
          comment_tag_name: "blog-posts"
          max_post_count: 5
